export default {
	br: 'Portuguese',
	ru: 'Russian',
	gr: 'Greek',
	jp: 'Japanese',
	pl: 'Polish',
	it: 'Italian',
	sa: 'Arabic',
	es: 'Spanish',
	il: 'Hebrew',
	fr: 'French',
	nl: 'Dutch',
	cn: 'Chinese',
	cz: 'Czech',
	kr: 'Korean',
	de: 'German',
	en: 'English',
	tr: 'Turkish',
	ir: 'Farsi',
	am: 'Armenian',
	in: 'Hindi',
};
